title: Bengünur Baş
subtitle: A green cat that travels the known world 
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal site . I am here to have fun what about you ? -_^

url: "https://bengunur06.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
#    - text: Shop
#      url : /shop
    - text: Contact Me
      url : /contact
#   - text: Styleguide
#      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Bengünur Baş
author_bio: A green cat that codes and  travels the known world .I like watching stars and wonder about my life . I took very long walks as hobby too walking across cities is a relaxing situation for me 
author_email: "bengunur2@gmail.com"
author_location: Andromeda
author_website_url: "https://bengunur06.github.io/"
typewrite-text:  A green cat that codes and  travels the known world .I am here to have fun what about you ? -_^

author_work_experiences:
            - company_name: Özgür Yazılım A.Ş.
              company_logo: oyas_fb.png
              company_url: https://ozguryazilim.com.tr/
              designation: GNU/Linux System administrator Intern
              description: I worked with CentOS7 server clusters to upgrade and maintain MongoDB,PostgresSQL, Zabbix.Dates :01/2019 – 06/2019 Ankara, Turkey
              visibility: true
            - company_name: Özgür Yazılım A.Ş.
              company_logo: oyas_fb.png
              company_url: https://ozguryazilim.com.tr/
              designation: GNU/Linux System administrator Intern
              description: I migrated CentOS servers on the KVM environment and configured DNS server settings.Dates :07/2020 – 08/2020 Ankara, Turkey
              visibility: true

author_education_details:
              - college_logo: anku-logo.png
                college_name: Ankara University
                college_url: https://www.ankara.edu.tr/
                college_degree: Computer Engineering
                description: Bachelor of Technology ,Programming with C,C++ /Object Oriented Programming /Data Structures /Data Bases (SQL) /Economy (macro-micro)/ Professional English / Programming Languages /Computer Graphisc /Network /Digital Logic
                visibility: true
              - college_logo: unisannio-logo.png
                college_name: Ankara University
                college_url: https://www.unisannio.it/
                college_degree: Computer Engineering
                description: Bachelor of Technology ,I was an Erasmus exchange student in Unisannio.the lectures I take were Artificial intelligence, Production Systems, Android Programming
                visibility: true

##
#author_project_details:
#              - project_thumbnail: gamershub.png
#                project_title: Gamers Hub
#                project_description: A Platform built for Gamers and Game Devs
#                project_url: https://gamershub.in
#                visibility: true
#              - project_thumbnail: hack4r.PNG
#                project_title: Hack4r
#                project_description: A Platform built for Hackers and Penetration Testers
#                project_url: https://hack4r.com
#                visibility: true
##
# social links
twitter_username: kiwisareok
github_username:  bengunur06
#facebook_username: johndoe
linkedin_username: bengünur-baş
behance_username: johndoe
instagram_username: rainfrog6
#medium_username: johndoe
telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: bengunur2@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
